name: Publish package

on:
  workflow_dispatch:
    inputs:
      package:
        type: choice
        description: 'Select a package'
        required: true
        default: '@storevent/storevent'
        options:
          - '@storevent/storevent'
          - '@storevent/storevent-pg'
          
      versionNumber:
        type: text
        description: 'Type version number'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Publish
        run: |
          echo "Publishing package: ${{ github.event.inputs.package }}@${{ github.event.inputs.versionNumber }}"
