name: Publish package

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      package:
        type: choice
        description: 'Select a package'
        required: true
        default: 'storevent'
        options:
          - 'storevent'
          - 'storevent-pg'
          - 'storevent-memory'


      releaseType:
        description: 'Release type'
        required: true
        type: choice
        default: patch
        options:
          - patch
          - minor
          - major

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          set-safe-directory: $GITHUB_WORKSPACE

      - name: Git setup
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.18.0
          registry-url: "https://registry.npmjs.org"
          scope: "storevent"

      - name: Install dependencies
        run: |
          node --version
          npm --version
          npm ci

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Run all tasks for package @storevent/${{ github.event.inputs.package }}
        run: npm run all -- --filter=@storevent/${{ github.event.inputs.package }}

      - name: Update ${{ github.event.inputs.package }} version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # NPM bug here: npm version will not create commit or tag if package is in a subdorectory.
          # Create a fake .git in sub folder to allow npm version to create the commit and tag
        run: |
          mkdir ./packages/${{ github.event.inputs.package }}/.git
          npm version ${{ github.event.inputs.releaseType }} -m "ci(publish): bump @storevent/${{ github.event.inputs.package }} version to %s" --workspace=@storevent/${{ github.event.inputs.package }}

      - name: Push changes and tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add .
          git push --follow-tags

      - name: Publish @storevent/${{ github.event.inputs.package }} to NPM
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm publish --access public --workspace=@storevent/${{ github.event.inputs.package }}


