name: Publish package

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      package:
        type: choice
        description: 'Select a package'
        required: true
        default: '@storevent/storevent'
        options:
          - '@storevent/storevent'
          - '@storevent/storevent-pg'

      releaseType:
        description: 'Release type'
        required: true
        type: choice
        default: patch
        options:
          - patch
          - minor
          - major

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:

      - name: Debug
        run: |
          echo $GITHUB_WORKSPACE
          ls -alh

      - name: Check out code
        uses: actions/checkout@v4
        with:
          set-safe-directory: $GITHUB_WORKSPACE

      - name: Debug
        run: |
          ls -alh

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.18.0

      - name: Install dependencies
        run: |
          node --version
          npm --version
          npm ci

      - name: Run all tasks for package ${{ github.event.inputs.package }}
        run: npm run all -- --filter=${{ github.event.inputs.package }}

      - name: Debug
        run: |
          git status

      - name: Update ${{ github.event.inputs.package }} version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm version ${{ github.event.inputs.releaseType }} -m "build(publish): publish ${{ github.event.inputs.package }} %s" --workspace=${{ github.event.inputs.package }}

      - name: Debug
        run: |
          git status

      - name: Push changes and tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add -A
          git push --follow-tags

      # - name: Publish ${{ github.event.inputs.package }} to NPM
      #   env:
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      #   run: |
      #     npm publish --workspace=${{ github.event.inputs.package }}


