name: Publish package

on:
  workflow_dispatch:
    inputs:
      package:
        description: 'Select a package'
        required: true
        default: '@storevent/storevent'
        options:
          - storevent
          - storevent-pg
          
      versionNumber:
        description: 'Type version number'
        required: true

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Publish
        run: |
          echo "Publishing: ${{ github.event.inputs.package }}@${{ github.event.inputs.package }}"
